/* 9. Написать скрипт вывода клиентов пенсионного возраста (мужчины 60 лет, женщины
55 лет). // Предполагаю что имелось в виду мужчины >= 60 и женщины >= 55 */

USE KCDB
GO

DECLARE @CURRENT_DATE DATE = GETDATE()
DECLARE @55YRS_BACK DATE = DateAdd(YY, -55, @CURRENT_DATE)
DECLARE @60YRS_BACK DATE = DateAdd(YY, -60, @CURRENT_DATE)

DECLARE @myTableVariable TABLE (client_id INT NOT NULL, first_name varchar(255), middle_name varchar(255), last_name varchar(255))

-- смотрим всех людей от 55
DECLARE @CLIENT_ID int,
		@CLIENT_BIRTHDATE DATE

SET @CLIENT_ID = (SELECT MIN(ID_CLIENT)
FROM CLIENTS_ADDFL_STRING
WHERE ID_FIELD = 1)

SET @CLIENT_BIRTHDATE = (SELECT MIN(FIELD)
FROM CLIENTS_ADDFL_STRING
WHERE ID_CLIENT = @CLIENT_ID AND ID_FIELD = 4)

WHILE @CLIENT_ID IS NOT NULL
BEGIN
	-- если человеку от 60 и более - вносим его сразу
	IF (@CLIENT_BIRTHDATE <= @60YRS_BACK)
	BEGIN
		DECLARE @CLIENT_FIRSTNAME varchar(255) = (SELECT FIRST_NAME
		FROM CLIENTS
		WHERE ID_CLIENT = @CLIENT_ID)
		DECLARE @CLIENT_MIDDLENAME varchar(255) = (SELECT MIDDLE_NAME
		FROM CLIENTS
		WHERE ID_CLIENT = @CLIENT_ID)
		DECLARE @CLIENT_LASTNAME varchar(255) = (SELECT LAST_NAME
		FROM CLIENTS
		WHERE ID_CLIENT = @CLIENT_ID)

		INSERT INTO @myTableVariable values(@CLIENT_ID, @CLIENT_FIRSTNAME, @CLIENT_MIDDLENAME, @CLIENT_LASTNAME)
	END
	ELSE IF (@CLIENT_BIRTHDATE <= @55YRS_BACK)-- если нет - проверяем есть ему 55... 
	BEGIN
		DECLARE @CLIENT_GENDER varchar = (SELECT FIELD -- ...и яляется ли он женщиной
		FROM CLIENTS_ADDFL_STRING WHERE ID_FIELD = 1 AND ID_CLIENT = @CLIENT_ID)
			
		IF (@CLIENT_GENDER = 'Ж')
		BEGIN
			SET @CLIENT_FIRSTNAME = (SELECT FIRST_NAME
			FROM CLIENTS
			WHERE ID_CLIENT = @CLIENT_ID)
			SET @CLIENT_MIDDLENAME = (SELECT MIDDLE_NAME
			FROM CLIENTS
			WHERE ID_CLIENT = @CLIENT_ID)
			SET @CLIENT_LASTNAME = (SELECT LAST_NAME
			FROM CLIENTS
			WHERE ID_CLIENT = @CLIENT_ID)

			INSERT INTO @myTableVariable values(@CLIENT_ID, @CLIENT_FIRSTNAME, @CLIENT_MIDDLENAME, @CLIENT_LASTNAME)
		END
	END
	
	SET @CLIENT_ID = (SELECT MIN(ID_CLIENT)
	FROM CLIENTS_ADDFL_STRING
	WHERE (ID_FIELD = 4 AND (CONVERT(DATE, FIELD) <= @55YRS_BACK)) AND (ID_CLIENT > @CLIENT_ID))

	SET @CLIENT_BIRTHDATE = (SELECT MIN(FIELD)
	FROM CLIENTS_ADDFL_STRING
	WHERE ID_CLIENT = @CLIENT_ID AND ID_FIELD = 4)
END

SELECT * FROM @myTableVariable